import type { Metadata } from "next";
import { Open_Sans } from 'next/font/google'
import "./globals.css";
import Sidebar from "@/components/Sidebar";

const openSans = Open_Sans({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "WaveMakers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <Sidebar>
          {children}
        </Sidebar>
      </body>
    </html>
  );
}
