import type { Metadata } from "next";
import { Open_Sans } from 'next/font/google'
import ".././globals.css";

const openSans = Open_Sans({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Next Dashboard",
  description: "Generated by create next app",
};

export default function AuthLayout({
    children,
}: {
    children: React.ReactNode;
}){
    return (
        <html lang="en" className="h-full bg-white">
            <body className={`${openSans.className} h-full`}>
                <div>
                    {children}
                </div>
            </body>
    </html>
    );
}